### ISSUE TITLE
fp.js and mmh3 different hashes

### ISSUE THREAD

**Issue by zxcvqwerasdf** [davidbaszucki/py-funcaptcha#2]
```
ife_hash = mmh3.hash_bytes("TestString", 38)
print(ife_hash.hex())

with open("fp.js") as f:
    mm3js = execjs.compile(f.read())
ife_hash_2 = mm3js.call("x64hash128", "TestString", 38)
print(ife_hash_2)
```
output:
bee0186cd9f50768aeb4763c41ca7348
6807f5d96c18e0be4873ca413c76b4ae

I checked "TestString" on some online murmurhash3 and get second hash (from fp.js)
So, which hash is correct?

**Comment by davidbaszucki** [comment]
Just looked into this and it seems like you're right indeed, mmh3 doesn't produce the same output as the javascript functions used by ArkoseLabs.

This could also explain why my solver has been stuck at 10 images per challenge for so long.

I'll look into a solution

**Comment by davidbaszucki** [comment]
After taking a closer look, this does not seem to be a problem as of now.

**Comment by zxcvqwerasdf** [comment]
Okay, thx for response, but it's strange.
