### ISSUE TITLE
encrypted_mode / duck game / about audio challenge

### ISSUE THREAD

**Issue by hashtafak** [davidbaszucki/py-funcaptcha#3]
Hello, I have some question:

1. encrytped_mode
I also manual input nc_resp in create_challenge() and it seems working well now. But then next issues I got =>

2. duck game
I always got duck game / gameType:1 / rotating game and demo example code always fails to solve (incorrect). Do you have any idea/update on it?

3. how to pass an audio challenge?
I tried to submit audio challenge and can't pass this

```
{
  response: 'disabled',
  message: 'Audio challenge methods require some extra steps. This is because of security precautions. We are sorry for the inconvenience. Please use the Help button and find the FAQ about audio accessibility.'
}
```

Thanks.

P/s: I am javascript side, not python side so it's a bit hard to fast edit code.

**Comment by davidbaszucki** [comment]
The demo example code won't work in a real scenario, it is simply there to showcase attributes and such.

I'm not sure about audio challenges.
